<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>Shared.Application</RootNamespace>
		<AssemblyName>Shared.Application</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Shared.Domain\Shared.Domain.csproj" />
	</ItemGroup>

</Project>
