/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Identity.WebAPI | v1
 * OpenAPI spec version: 1.0.0
 */
import { axiosInstance } from './axios-instance';
export interface AccountInfoDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: number | string;
  name?: string;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  phoneNum?: string | null;
}

export interface CreateAccountInfoCommand {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  phoneNum?: string | null;
  password?: string;
}

export interface GetAccountInfoQuery {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: number | string;
}

export interface LoginCommand {
  identity?: string;
  password?: string;
  /** @nullable */
  ipAddress?: string | null;
}

export interface LoginResponseDto {
  user?: AccountInfoDto;
  accessToken?: string;
  refreshToken?: string;
  expiresAt?: string;
}

export interface LogoutCommand {
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  accountInfoId?: number | string | null;
  refreshToken?: string;
  /** @nullable */
  ipAddress?: string | null;
}

export interface PaginatedListOfAccountInfoDto {
  items: AccountInfoDto[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageNumber: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalPages?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalCount?: number | string;
  hasPreviousPage?: boolean;
  hasNextPage?: boolean;
}

export interface RefreshTokenCommand {
  accessToken?: string;
  refreshToken?: string;
}

export interface SearchAccountInfosQuery {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageNumber?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageSize?: number | string;
}

export interface UpdateAccountInfoCommand {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: number | string;
  email?: string;
  password?: string;
}

export const getIdentityWebAPIV1 = () => {
const postIdentityAccountInfosGet = (
    getAccountInfoQuery: GetAccountInfoQuery,
 ) => {
      return axiosInstance<AccountInfoDto>(
      {url: `/identity/AccountInfos/Get`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getAccountInfoQuery
    },
      );
    }

const postIdentityAccountInfos = (
    createAccountInfoCommand: CreateAccountInfoCommand,
 ) => {
      return axiosInstance<number | string>(
      {url: `/identity/AccountInfos`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createAccountInfoCommand
    },
      );
    }

const deleteIdentityAccountInfosId = (
    id: number | string,
 ) => {
      return axiosInstance<void>(
      {url: `/identity/AccountInfos/${id}`, method: 'DELETE'
    },
      );
    }

const putIdentityAccountInfosId = (
    id: number | string,
    updateAccountInfoCommand: UpdateAccountInfoCommand,
 ) => {
      return axiosInstance<void>(
      {url: `/identity/AccountInfos/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateAccountInfoCommand
    },
      );
    }

const postIdentityAccountInfosSearch = (
    searchAccountInfosQuery: SearchAccountInfosQuery,
 ) => {
      return axiosInstance<PaginatedListOfAccountInfoDto>(
      {url: `/identity/AccountInfos/Search`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: searchAccountInfosQuery
    },
      );
    }

const postIdentityAuthorizationsLogin = (
    loginCommand: LoginCommand,
 ) => {
      return axiosInstance<LoginResponseDto>(
      {url: `/identity/Authorizations/Login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginCommand
    },
      );
    }

const postIdentityAuthorizationsRefreshToken = (
    refreshTokenCommand: RefreshTokenCommand,
 ) => {
      return axiosInstance<void>(
      {url: `/identity/Authorizations/RefreshToken`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshTokenCommand
    },
      );
    }

const postIdentityAuthorizationsLogout = (
    logoutCommand: LogoutCommand,
 ) => {
      return axiosInstance<void>(
      {url: `/identity/Authorizations/Logout`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: logoutCommand
    },
      );
    }

return {postIdentityAccountInfosGet,postIdentityAccountInfos,deleteIdentityAccountInfosId,putIdentityAccountInfosId,postIdentityAccountInfosSearch,postIdentityAuthorizationsLogin,postIdentityAuthorizationsRefreshToken,postIdentityAuthorizationsLogout}};
export type PostIdentityAccountInfosGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getIdentityWebAPIV1>['postIdentityAccountInfosGet']>>>
export type PostIdentityAccountInfosResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getIdentityWebAPIV1>['postIdentityAccountInfos']>>>
export type DeleteIdentityAccountInfosIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getIdentityWebAPIV1>['deleteIdentityAccountInfosId']>>>
export type PutIdentityAccountInfosIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getIdentityWebAPIV1>['putIdentityAccountInfosId']>>>
export type PostIdentityAccountInfosSearchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getIdentityWebAPIV1>['postIdentityAccountInfosSearch']>>>
export type PostIdentityAuthorizationsLoginResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getIdentityWebAPIV1>['postIdentityAuthorizationsLogin']>>>
export type PostIdentityAuthorizationsRefreshTokenResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getIdentityWebAPIV1>['postIdentityAuthorizationsRefreshToken']>>>
export type PostIdentityAuthorizationsLogoutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getIdentityWebAPIV1>['postIdentityAuthorizationsLogout']>>>
