/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * WebAPI | v1
 * OpenAPI spec version: 1.0.0
 */
import { axiosInstance } from './axios-instance';
export interface CreateUserProfileCommand {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  phoneNum?: string | null;
  password?: string;
}

export interface GetUserProfileQuery {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: number | string;
}

export interface LoginRequestDto {
  identity: string;
  password: string;
}

export interface LogoutRequestDto {
  refreshToken: string;
}

export interface UserProfileBriefDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: number | string;
  name?: string;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  phoneNum?: string | null;
}

export interface PaginatedListOfUserProfileBriefDto {
  items: UserProfileBriefDto[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageNumber: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalPages?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalCount?: number | string;
  hasPreviousPage?: boolean;
  hasNextPage?: boolean;
}

export interface RefreshTokenRequestDto {
  accessToken: string;
  refreshToken: string;
}

export interface SearchUserProfilesQuery {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageNumber?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pageSize?: number | string;
}

export interface UpdateUserProfileCommand {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: number | string;
  email?: string;
  password?: string;
}

export const getWebAPIV1 = () => {
const postUserAuthsLogin = (
    loginRequestDto: LoginRequestDto,
 ) => {
      return axiosInstance<void>(
      {url: `/user/Auths/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequestDto
    },
      );
    }

const postUserAuthsRefreshToken = (
    refreshTokenRequestDto: RefreshTokenRequestDto,
 ) => {
      return axiosInstance<void>(
      {url: `/user/Auths/refresh-token`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshTokenRequestDto
    },
      );
    }

const postUserAuthsLogout = (
    logoutRequestDto: LogoutRequestDto,
 ) => {
      return axiosInstance<void>(
      {url: `/user/Auths/logout`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: logoutRequestDto
    },
      );
    }

const postUserUserProfilesGet = (
    getUserProfileQuery: GetUserProfileQuery,
 ) => {
      return axiosInstance<UserProfileBriefDto>(
      {url: `/user/UserProfiles/Get`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getUserProfileQuery
    },
      );
    }

const postUserUserProfiles = (
    createUserProfileCommand: CreateUserProfileCommand,
 ) => {
      return axiosInstance<number | string>(
      {url: `/user/UserProfiles`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createUserProfileCommand
    },
      );
    }

const deleteUserUserProfilesId = (
    id: number | string,
 ) => {
      return axiosInstance<void>(
      {url: `/user/UserProfiles/${id}`, method: 'DELETE'
    },
      );
    }

const putUserUserProfilesId = (
    id: number | string,
    updateUserProfileCommand: UpdateUserProfileCommand,
 ) => {
      return axiosInstance<void>(
      {url: `/user/UserProfiles/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateUserProfileCommand
    },
      );
    }

const postUserUserProfilesSearch = (
    searchUserProfilesQuery: SearchUserProfilesQuery,
 ) => {
      return axiosInstance<PaginatedListOfUserProfileBriefDto>(
      {url: `/user/UserProfiles/Search`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: searchUserProfilesQuery
    },
      );
    }

return {postUserAuthsLogin,postUserAuthsRefreshToken,postUserAuthsLogout,postUserUserProfilesGet,postUserUserProfiles,deleteUserUserProfilesId,putUserUserProfilesId,postUserUserProfilesSearch}};
export type PostUserAuthsLoginResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWebAPIV1>['postUserAuthsLogin']>>>
export type PostUserAuthsRefreshTokenResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWebAPIV1>['postUserAuthsRefreshToken']>>>
export type PostUserAuthsLogoutResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWebAPIV1>['postUserAuthsLogout']>>>
export type PostUserUserProfilesGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWebAPIV1>['postUserUserProfilesGet']>>>
export type PostUserUserProfilesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWebAPIV1>['postUserUserProfiles']>>>
export type DeleteUserUserProfilesIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWebAPIV1>['deleteUserUserProfilesId']>>>
export type PutUserUserProfilesIdResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWebAPIV1>['putUserUserProfilesId']>>>
export type PostUserUserProfilesSearchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getWebAPIV1>['postUserUserProfilesSearch']>>>
