<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>Identity.Application</RootNamespace>
		<AssemblyName>Identity.Application</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Shared\src\Shared.Application\Shared.Application.csproj" />
		<ProjectReference Include="..\Domain\Domain.csproj" />
	</ItemGroup>

</Project>
